package java_collections;

public enum Genre {
    FANTASY,
    SCI_FI,
    HISTORY,
    ADVENTURE,
    CRIME,
    HORROR,
    ACTION, INDIE, RPG, STRATEGY, CASUAL, SPORTS, MASSIVELY_MULTIPLAYER, FREE_TO_PLAY, SIMULATION, EARLY_ACCESS, RACING, UTILITIES, YOUNG_ADULT
}
